Mint Sign-Up Page
KinezaEnaelle/Mint-Signup pull request #1
Opened 2020-09-18 13:03 UTC by KinezaEnaelle

This is a data collection form designed by Uchenna Martins Anya and Iris Enaelle Kineza, using HTML5 and CSS3.

2020-09-18 15:42 UTC, jubaan requested changes
# Status: Changes Required 

## :clap::clap::clap::clap: Amazin work!! The website looks pretty similar to the original one. 

Things to notice:
:100: Using semantic HTML for main sections and elements of the form.
:100: README descriptive enough
:100: Link to Live Preview! this made my life more easier! thank you :smiley: !!!

## Changes Required

### [Mandatory]
- [ ] Project not passing all linter's checks. 

- [ ] Remove unnecessary files form project. Only upload the ones related to the project.
![image](https://user-images.githubusercontent.com/25774518/93613136-128f1900-f996-11ea-9097-72888f2b028f.png)

- [ ] Remove all inline styling from HTML and assign it as a selector in the CSS file. Is best practice to use a stylesheet for all styling purposes. This helps also debugging the CSS if something is not displaying correctly. 
![image](https://user-images.githubusercontent.com/25774518/93615447-05bff480-f999-11ea-8416-7c9deaf55415.png)


### [OPTIONAL]

- [ ] Improve the link name to the live preview. Something similar to this example:

[Mint sign-up page clone](https://rawcdn.githack.com/KinezaEnaelle/Mint-Signup/a945d8e625863ffe14e6a76fa53725a5b92dc06a/index.html)

- [ ] Try removing the ```<div>``` tag that wraps the ```<label>``` html tag.

- [ ] Prefer CSS classes over general selectors. As it is more specific. Example:

:-1:  From this pattern
```
header button {
    ... properties
}
```
:+1: to this
```
.header_btn {
    ... properties ...
}
```

- [ ] For future projects try to make Commit Messages more descriptive. This will help the reader understand the decisions and changes made in the past, and grasp a better understanding of what the programmer wanted to do. Example:

:-1:  From this. This makes the reader wonder what was the change referring to.
```
Readme
```
:+1: to This. Still short but the reader and you can follow the changes made.
```
Update: add contact info to README
```

## Keep up the great work :muscle:, and Happy coding :smiley: :computer: !!!

2020-09-18 18:01 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Good job fixing the linters, team! 👍 
Very good use of semantic HTML, and your code is clean 💯 
But we still some required changes to implement.
As the previous TSE pointed before, kindly make the following changes:

- Avoid inline styling, it is a better practice to add CSS classes.
- Remove unnecessary files form project. Add them to `.gitignore`
- Use a form tag to wrap your form. It is the way you can submit and manage the data the user inputs.
   - It uses a `<form>` tag ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))


[OPTIONAL]
- It is a better practice to add some CSS classes and not to use general selectors to style the content of your page.

# Keep it up!! 💪

2020-09-21 08:33 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet.😟 You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [x] Your PR is not descriptive. Please add more about your project in the PR message. This is a place where you can tell TSEs what you di din this project what you are proud of and what you additionally added.

- [x] mint, QuickBooks, and TurboTax icons should have a text with them. You cannot add only images there. 
![chrome-capture (1)](https://user-images.githubusercontent.com/58504655/93745807-9141bb80-fc0d-11ea-9f39-9d058c688396.jpg)

- [x] You should use form tag to warp form elements like inputs, labels, etc as suggested by previous TSE.

- [x] **Optional** please try to add the link into one or two works like [Live demo](https://rawcdn.githack.com/KinezaEnaelle/Mint-Signup/a945d8e625863ffe14e6a76fa53725a5b92dc06a/index.html)
![chrome-capture (2)](https://user-images.githubusercontent.com/58504655/93746120-08774f80-fc0e-11ea-9e4f-13b70fc526c0.jpg)

- [ ] **Optional** About section is not descriptive. Please tell within 1-2 lines what you did in this project and what technologies you used, etc 


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-09-21 08:33 UTC, arslanbisharat commented on README.md
> +
your link should be wrapped in one to two words

2020-09-21 08:33 UTC, arslanbisharat commented on index.html
> +          </section>
Please use **form** tag

2020-09-21 08:33 UTC, arslanbisharat commented on index.html
> +        </div>
It shows the Mint logo and text (logo on the left, text on the right) 

 It shows the Quickbooks logo and text (logo on the left, text on the right

 It shows the Turbotax logo and text (logo on the left, text on the right)

2020-09-21 16:32 UTC, javitocor requested changes
# CHANGES REQUIRED ♻️ 

Great job implementing all the changes! 👍 
The linters still green, well done! 💚 
I can see you have been working hard in this project 💪 
Just one more thing to get the project approved and move forward ⏩ 
Let's make all the projects to be as professional as we can, we want to have good repositories when a professional recruiter comes to take a look at it,  we want them to get impressed.
## Changes
- Your live link is not updated, I cannot see the form tag in it, you made the changes in your repo, and we want that anyone who checks the live link and inspect it, will be able to see that you can use semantic HTML tags. Kindly update it

Once you have implemented the change, please resubmit for a new code review and move forward into the next project.

Good luck 😃

2020-09-21 16:58 UTC, javitocor approved these changes
# STATUS APPROVED 🌟 🥇 

Really good job guys 👍 
You have met all the requirements! 💯 

Remember to submit the completion form and you can move forward into the next project ⏩ 

Good luck 😃

2020-09-21 17:00 UTC, merged